### ISSUE TITLE
Cursor moves to beginning after editing the html

### ISSUE THREAD

**Issue by jkoenig134** [pleku/wysiwyg-e-java#10]
Is there a possibility to move the cursor to the end of the input field?

**Comment by pleku** [comment]
Hi. Not yet, but it should be possible to add API for that.

**Comment by jkoenig134** [comment]
Hey @pleku thanks for your work! I love this plugin. 
When do you plan to finish 2.1.0?

**Comment by pleku** [comment]
@jkoenig134 this is a community project for me, so I work on it occasionally when there is nothing critical going on. My guestimate is that I will take a look on the requested features for 2.1.0 in next 1-3 weeks.

**Comment by pleku** [comment]
> My guestimate is that I will take a look on the requested features for 2.1.0 in next 1-3 weeks.

Sorry, more like 1-3 months so hopefully I can make something happen in February by the latest.

**Comment by jkoenig134** [comment]
Sounds great, thank you!
